#!/bin/bash
set -euo pipefail

usage() {
  echo "Usage: aoc [day] [-d] [-e [example number]|-i <input file name>]"
}

# cd to directory of this script (repository root)
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
source ./lib.sh

input_name=input.txt
day=$(date +%-d)
debug=n

first_iter=y
while [[ $# -gt 0 ]]; do
  case $1 in
    -d|--debug)
      debug=y
      shift
      ;;
    -e|--example)
      input_name=example1.txt
      if [[ $# -gt 1 ]]; then
        # example number given
        input_name=example$2.txt
        shift
      fi
      shift
      ;;
    -i|--input)
      input_name=$2
      shift
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "Error: unrecognized option '$1'"
      usage
      exit 1
      ;;
    *)
      if [[ $first_iter == y ]]; then
        day=$1
        shift
      else
        echo "Error: day can only be in the first argument"
        usage
        exit 1
      fi
      ;;
  esac
  first_iter=n
done

binary=bin/day$day
if [[ $debug == y ]]; then
  binary=$binary.debug
fi

# rebuild if make says it's necessary
make_quiet "$binary"

echo "Day $day:"
# run on the specified input
"$binary" "input/day$day/$input_name"
