#!/bin/bash
set -euo pipefail

iwyu_tool.py -p . "$@" -- --no-warnings -Xiwyu --quoted_includes_first -Xiwyu --max_line_length=300 -Xiwyu --mapping_file=iwyu_mappings.imp -resource-dir "$(clang -print-resource-dir)"
